# Data Importing

In [8]:
import pandas as pd 
import numpy as np

In [9]:
amazon = pd.read_csv("Amazon Sale Report.csv",low_memory=False)
sale = pd.read_csv("Sale Report.csv")
may = pd.read_csv("May-2022.csv")

# Understand the dataset

In [10]:
amazon.head(5)
sale.head(5)
may.head(5)

,index,Sku,Style Id,Catalog,Category,Weight,TP,MRP Old,Final MRP Old,Ajio MRP,Amazon MRP,Amazon FBA MRP,Flipkart MRP,Limeroad MRP,Myntra MRP,Paytm MRP,Snapdeal MRP
0,0,Os206_3141_S,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
1,1,Os206_3141_M,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
2,2,Os206_3141_L,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
3,3,Os206_3141_XL,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
4,4,Os206_3141_2XL,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295

In [11]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [6]:
amazon.shape
sale.shape
may.shape

(1330, 17)

# Data Cleaning

In [7]:
amazon.isnull().sum()
may.isnull().sum()
sale.isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [8]:
amazon.columns = amazon.columns.str.strip()

In [9]:
amazon.drop(columns=['index','fulfilled-by','promotion-ids','Unnamed: 22'], inplace=True)

In [10]:
amazon.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'B2B'],
      dtype='object')

In [11]:
# Fill missing values
amazon['currency'] = amazon['currency'].fillna("INR")

In [12]:
# Fill Amount columns
amazon['Amount'] = amazon['Amount'].fillna(amazon['Amount'].mean())
amazon['Amount']

0          647.62
1          406.00
2          329.00
3          753.33
4          574.00
           ...
128970     517.00
128971     999.00
128972     690.00
128973    1199.00
128974     696.00
Name: Amount, Length: 128975, dtype: float64

In [13]:
# Fill Courier Status
amazon['Courier Status'] = amazon['Courier Status'].fillna('Unknown')

In [14]:
# Fill location columns
amazon['ship-city'] = amazon['ship-city'].fillna('Unknown')
amazon['ship-state'] = amazon['ship-state'].fillna('Unknown')
amazon['ship-postal-code'] = amazon['ship-postal-code'].fillna('Unknown')
amazon['ship-country'] = amazon['ship-country'].fillna('Unknown')

In [15]:
amazon.isnull().sum()

Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
B2B                   0
dtype: int64

In [16]:
# Amazon dataset
amazon.duplicated().sum()

6

In [17]:
# Remove duplicated
amazon = amazon.drop_duplicates()

In [18]:
amazon.duplicated().sum()

0

In [19]:
# Check Current Column Names
amazon.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'B2B'],
      dtype='object')

In [20]:
# Change column names
amazon.rename(columns={
    'Qty':'Quantity',
    'ship-city':'City',
    'ship-state':'State',
    'ship-country':'Country',
    'ship-postal-code':'postal_code',
}, inplace = True)

In [21]:
amazon.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Quantity', 'currency', 'Amount', 'City', 'State',
       'postal_code', 'Country', 'B2B'],
      dtype='object')

In [22]:
amazon.columns = amazon.columns.str.strip().str.replace(" ", "_").str.replace("-", "_").str.lower()

In [23]:
amazon.rename(columns={'Sales_Channel_':'Sales_Channel'}, inplace=True)

In [24]:
amazon.columns

Index(['order_id', 'date', 'status', 'fulfilment', 'sales_channel',
       'ship_service_level', 'style', 'sku', 'category', 'size', 'asin',
       'courier_status', 'quantity', 'currency', 'amount', 'city', 'state',
       'postal_code', 'country', 'b2b'],
      dtype='object')

In [25]:
amazon.dtypes

order_id               object
date                   object
status                 object
fulfilment             object
sales_channel          object
ship_service_level     object
style                  object
sku                    object
category               object
size                   object
asin                   object
courier_status         object
quantity                int64
currency               object
amount                float64
city                   object
state                  object
postal_code            object
country                object
b2b                      bool
dtype: object

In [26]:
# Convert Date Column
amazon['date'] = pd.to_datetime(amazon['date'])

C:\Users\ac606\AppData\Local\Temp\ipykernel_436\4118445268.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amazon['date'] = pd.to_datetime(amazon['date'])

In [27]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128969 entries, 0 to 128974
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            128969 non-null  object
 1   date                128969 non-null  datetime64[ns]
 2   status              128969 non-null  object
 3   fulfilment          128969 non-null  object
 4   sales_channel       128969 non-null  object
 5   ship_service_level  128969 non-null  object
 6   style               128969 non-null  object
 7   sku                 128969 non-null  object
 8   category            128969 non-null  object
 9   size                128969 non-null  object
 10  asin                128969 non-null  object
 11  courier_status      128969 non-null  object
 12  quantity            128969 non-null  int64
 13  currency            128969 non-null  object
 14  amount              128969 non-null  float64
 15  city                128969 non-null  object
 16  state               128969 non-null  object
 17  postal_code         128969 non-null  object
 18  country             128969 non-null  object
 19  b2b                 128969 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(16)
memory usage: 19.8+ MB

In [28]:
amazon['month'] = amazon['date'].dt.month
amazon['year'] = amazon['date'].dt.year

In [29]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128969 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            128969 non-null  object
 1   date                128969 non-null  datetime64[ns]
 2   status              128969 non-null  object
 3   fulfilment          128969 non-null  object
 4   sales_channel       128969 non-null  object
 5   ship_service_level  128969 non-null  object
 6   style               128969 non-null  object
 7   sku                 128969 non-null  object
 8   category            128969 non-null  object
 9   size                128969 non-null  object
 10  asin                128969 non-null  object
 11  courier_status      128969 non-null  object
 12  quantity            128969 non-null  int64
 13  currency            128969 non-null  object
 14  amount              128969 non-null  float64
 15  city                128969 non-null  object
 16  state               128969 non-null  object
 17  postal_code         128969 non-null  object
 18  country             128969 non-null  object
 19  b2b                 128969 non-null  bool
 20  month               128969 non-null  int32
 21  year                128969 non-null  int32
dtypes: bool(1), datetime64[ns](1), float64(1), int32(2), int64(1), object(16)
memory usage: 20.8+ MB

In [30]:
# Clean sale report dataset
sale = pd.read_csv('Sale Report.csv')
sale.head()

   index       SKU Code Design No.  Stock       Category Size Color
0      0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1      1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2      2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red

In [31]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9271 entries, 0 to 9270
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9271 non-null   int64
 1   SKU Code    9188 non-null   object
 2   Design No.  9235 non-null   object
 3   Stock       9235 non-null   float64
 4   Category    9226 non-null   object
 5   Size        9235 non-null   object
 6   Color       9226 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 507.1+ KB

In [32]:
sale.isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [33]:
sale = sale.dropna()

In [34]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9188 entries, 0 to 9234
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9188 non-null   int64
 1   SKU Code    9188 non-null   object
 2   Design No.  9188 non-null   object
 3   Stock       9188 non-null   float64
 4   Category    9188 non-null   object
 5   Size        9188 non-null   object
 6   Color       9188 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 574.2+ KB

In [35]:
sale.shape

(9188, 7)

In [36]:
sale.dtypes

index           int64
SKU Code       object
Design No.     object
Stock         float64
Category       object
Size           object
Color          object
dtype: object

In [37]:
sale['Stock'] = sale['Stock'].astype('int64')

In [38]:
sale.dtypes

index          int64
SKU Code      object
Design No.    object
Stock          int64
Category      object
Size          object
Color         object
dtype: object

In [39]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9188 entries, 0 to 9234
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9188 non-null   int64
 1   SKU Code    9188 non-null   object
 2   Design No.  9188 non-null   object
 3   Stock       9188 non-null   int64
 4   Category    9188 non-null   object
 5   Size        9188 non-null   object
 6   Color       9188 non-null   object
dtypes: int64(2), object(5)
memory usage: 574.2+ KB

In [40]:
sale = sale.drop(columns = ['index'])

In [41]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9188 entries, 0 to 9234
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SKU Code    9188 non-null   object
 1   Design No.  9188 non-null   object
 2   Stock       9188 non-null   int64
 3   Category    9188 non-null   object
 4   Size        9188 non-null   object
 5   Color       9188 non-null   object
dtypes: int64(1), object(5)
memory usage: 502.5+ KB

In [42]:
sale.shape

(9188, 6)

In [43]:
# Check Duplicates
sale.duplicated().sum()

3

In [44]:
# Remove duplicates
sale = sale.drop_duplicates()

In [45]:
sale.duplicated().sum()

0

In [46]:
# Check columns
sale.columns

Index(['SKU Code', 'Design No.', 'Stock', 'Category', 'Size', 'Color'], dtype='object')

In [47]:
sale.columns = sale.columns.str.strip().str.replace(" ", "_").str.lower()

In [48]:
sale.columns

Index(['sku_code', 'design_no.', 'stock', 'category', 'size', 'color'], dtype='object')

In [49]:
sale.dtypes

sku_code      object
design_no.    object
stock          int64
category      object
size          object
color         object
dtype: object

In [50]:
# May dataset
may = pd.read_csv("May-2022.csv")
may.head()

,index,Sku,Style Id,Catalog,Category,Weight,TP,MRP Old,Final MRP Old,Ajio MRP,Amazon MRP,Amazon FBA MRP,Flipkart MRP,Limeroad MRP,Myntra MRP,Paytm MRP,Snapdeal MRP
0,0,Os206_3141_S,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
1,1,Os206_3141_M,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
2,2,Os206_3141_L,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
3,3,Os206_3141_XL,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295
4,4,Os206_3141_2XL,Os206_3141,Moments,Kurta,0.3,538,2178,2295,2295,2295,2295,2295,2295,2295,2295,2295

In [51]:
may.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           1330 non-null   int64
 1   Sku             1330 non-null   object
 2   Style Id        1330 non-null   object
 3   Catalog         1330 non-null   object
 4   Category        1330 non-null   object
 5   Weight          1330 non-null   object
 6   TP              1330 non-null   object
 7   MRP Old         1330 non-null   object
 8   Final MRP Old   1330 non-null   object
 9   Ajio MRP        1330 non-null   object
 10  Amazon MRP      1330 non-null   object
 11  Amazon FBA MRP  1330 non-null   object
 12  Flipkart MRP    1330 non-null   object
 13  Limeroad MRP    1330 non-null   object
 14  Myntra MRP      1330 non-null   object
 15  Paytm MRP       1330 non-null   object
 16  Snapdeal MRP    1330 non-null   object
dtypes: int64(1), object(16)
memory usage: 176.8+ KB

In [52]:
may.isnull().sum()

index             0
Sku               0
Style Id          0
Catalog           0
Category          0
Weight            0
TP                0
MRP Old           0
Final MRP Old     0
Ajio MRP          0
Amazon MRP        0
Amazon FBA MRP    0
Flipkart MRP      0
Limeroad MRP      0
Myntra MRP        0
Paytm MRP         0
Snapdeal MRP      0
dtype: int64

In [53]:
may.replace("Nill", np.nan, inplace=True)

In [54]:
may.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           1330 non-null   int64
 1   Sku             1330 non-null   object
 2   Style Id        1330 non-null   object
 3   Catalog         1257 non-null   object
 4   Category        1257 non-null   object
 5   Weight          1257 non-null   object
 6   TP              1330 non-null   object
 7   MRP Old         1293 non-null   object
 8   Final MRP Old   1293 non-null   object
 9   Ajio MRP        1293 non-null   object
 10  Amazon MRP      1293 non-null   object
 11  Amazon FBA MRP  1293 non-null   object
 12  Flipkart MRP    1293 non-null   object
 13  Limeroad MRP    1293 non-null   object
 14  Myntra MRP      1299 non-null   object
 15  Paytm MRP       1293 non-null   object
 16  Snapdeal MRP    1293 non-null   object
dtypes: int64(1), object(16)
memory usage: 176.8+ KB

In [55]:
may.isnull().sum()

index              0
Sku                0
Style Id           0
Catalog           73
Category          73
Weight            73
TP                 0
MRP Old           37
Final MRP Old     37
Ajio MRP          37
Amazon MRP        37
Amazon FBA MRP    37
Flipkart MRP      37
Limeroad MRP      37
Myntra MRP        31
Paytm MRP         37
Snapdeal MRP      37
dtype: int64

In [56]:
# Remove Duplicates
may = may.drop_duplicates()

In [57]:
may.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           1330 non-null   int64
 1   Sku             1330 non-null   object
 2   Style Id        1330 non-null   object
 3   Catalog         1257 non-null   object
 4   Category        1257 non-null   object
 5   Weight          1257 non-null   object
 6   TP              1330 non-null   object
 7   MRP Old         1293 non-null   object
 8   Final MRP Old   1293 non-null   object
 9   Ajio MRP        1293 non-null   object
 10  Amazon MRP      1293 non-null   object
 11  Amazon FBA MRP  1293 non-null   object
 12  Flipkart MRP    1293 non-null   object
 13  Limeroad MRP    1293 non-null   object
 14  Myntra MRP      1299 non-null   object
 15  Paytm MRP       1293 non-null   object
 16  Snapdeal MRP    1293 non-null   object
dtypes: int64(1), object(16)
memory usage: 176.8+ KB

In [58]:
may.isnull().sum()

index              0
Sku                0
Style Id           0
Catalog           73
Category          73
Weight            73
TP                 0
MRP Old           37
Final MRP Old     37
Ajio MRP          37
Amazon MRP        37
Amazon FBA MRP    37
Flipkart MRP      37
Limeroad MRP      37
Myntra MRP        31
Paytm MRP         37
Snapdeal MRP      37
dtype: int64

In [59]:
# Drop index column
may = may.drop(columns= ['index'])

In [60]:
may. columns

Index(['Sku', 'Style Id', 'Catalog', 'Category', 'Weight', 'TP', 'MRP Old',
       'Final MRP Old', 'Ajio MRP', 'Amazon MRP', 'Amazon FBA MRP',
       'Flipkart MRP', 'Limeroad MRP', 'Myntra MRP', 'Paytm MRP',
       'Snapdeal MRP'],
      dtype='object')

In [61]:
# Clean Column names
may.columns = may.columns.str.strip().str.replace(" ","_").str.lower()

In [62]:
may.columns

Index(['sku', 'style_id', 'catalog', 'category', 'weight', 'tp', 'mrp_old',
       'final_mrp_old', 'ajio_mrp', 'amazon_mrp', 'amazon_fba_mrp',
       'flipkart_mrp', 'limeroad_mrp', 'myntra_mrp', 'paytm_mrp',
       'snapdeal_mrp'],
      dtype='object')

In [63]:
# Handles missing values
may = may.dropna()

In [64]:
may.isnull().sum()

sku               0
style_id          0
catalog           0
category          0
weight            0
tp                0
mrp_old           0
final_mrp_old     0
ajio_mrp          0
amazon_mrp        0
amazon_fba_mrp    0
flipkart_mrp      0
limeroad_mrp      0
myntra_mrp        0
paytm_mrp         0
snapdeal_mrp      0
dtype: int64

In [65]:
# Check Data types
may.dtypes

sku               object
style_id          object
catalog           object
category          object
weight            object
tp                object
mrp_old           object
final_mrp_old     object
ajio_mrp          object
amazon_mrp        object
amazon_fba_mrp    object
flipkart_mrp      object
limeroad_mrp      object
myntra_mrp        object
paytm_mrp         object
snapdeal_mrp      object
dtype: object

In [66]:
# Convert Numeric columns
cols = ['weight','tp','mrp_old','final_mrp_old','ajio_mrp','amazon_mrp',
       'amazon_fba_mrp','flipkart_mrp','limeroad_mrp','myntra_mrp',
       'paytm_mrp','snapdeal_mrp']
may[cols] = may[cols].astype(float)

In [67]:
may.dtypes

sku                object
style_id           object
catalog            object
category           object
weight            float64
tp                float64
mrp_old           float64
final_mrp_old     float64
ajio_mrp          float64
amazon_mrp        float64
amazon_fba_mrp    float64
flipkart_mrp      float64
limeroad_mrp      float64
myntra_mrp        float64
paytm_mrp         float64
snapdeal_mrp      float64
dtype: object

In [68]:
# Check Duplicates
# Amazon dataset
amazon.duplicated().sum()
sale.duplicated().sum()
# may.duplicated().sum()

0

In [ ]:
# Merge files

In [69]:
amazon.rename(columns = {'SKU':'sku'},inplace = True)
sale.columns
# amazon.columns

Index(['sku_code', 'design_no.', 'stock', 'category', 'size', 'color'], dtype='object')

In [70]:
sale.rename(columns = {'sku_code':'sku'},inplace = True)

In [71]:
sales_analysis = pd.merge(amazon, sale, left_on='sku',right_on = 'sku', how='left')

In [72]:
# Step - 2 Merge Amazon + Sale
sales_analysis = pd.merge(amazon, sale, on ='sku', how ='left')

In [73]:
sales_analysis.shape

(128969, 27)

In [74]:
sales_analysis.head()

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category_x,size_x,...,postal_code,country,b2b,month,year,design_no.,stock,category_y,size_y,color
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,400081.0,IN,False,4,2022,SET389,32.0,SET,S,White
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,560085.0,IN,False,4,2022,JNE3781,96.0,KURTA,XXXL,Green
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,410210.0,IN,True,4,2022,JNE3371,4.0,KURTA,XL,Light Green
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,605008.0,IN,False,4,2022,J0341,193.0,DRESS,L,Blue
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,600073.0,IN,False,4,2022,JNE3671,6.0,TUNIC,XXXL,Pink

In [75]:
sales_analysis.isnull().sum()

order_id                 0
date                     0
status                   0
fulfilment               0
sales_channel            0
ship_service_level       0
style                    0
sku                      0
category_x               0
size_x                   0
asin                     0
courier_status           0
quantity                 0
currency                 0
amount                   0
city                     0
state                    0
postal_code              0
country                  0
b2b                      0
month                    0
year                     0
design_no.            7706
stock                 7706
category_y            7706
size_y                7706
color                 7706
dtype: int64

In [76]:
(sales_analysis['category_x'] == sales_analysis['category_y']).value_counts()

False    128969
Name: count, dtype: int64

In [77]:
(sales_analysis['size_x'] == sales_analysis['size_y']).value_counts()

True     106727
False     22242
Name: count, dtype: int64

In [78]:
sales_analysis.drop(['category_y'], axis=1, inplace=True)
sales_analysis.rename(columns={'category_x':'category'}, inplace=True)

In [79]:
sales_analysis['size'] = sales_analysis['size_x'].combine_first(sales_analysis['size_y'])
sales_analysis.drop(['size_x','size_y'], axis=1, inplace=True)

In [80]:
sales_analysis['design_no.'] = sales_analysis['design_no.'].fillna("Unknown")
sales_analysis['category'] = sales_analysis['category'].fillna("Unknown")
sales_analysis['size'] = sales_analysis['size'].fillna("Unknown")
sales_analysis['color'] = sales_analysis['color'].fillna("Unknown")

sales_analysis['stock'] = sales_analysis['stock'].fillna(0)

In [81]:
sales_analysis.isnull().sum()

order_id              0
date                  0
status                0
fulfilment            0
sales_channel         0
ship_service_level    0
style                 0
sku                   0
category              0
asin                  0
courier_status        0
quantity              0
currency              0
amount                0
city                  0
state                 0
postal_code           0
country               0
b2b                   0
month                 0
year                  0
design_no.            0
stock                 0
color                 0
size                  0
dtype: int64

In [82]:
sales_analysis

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,asin,...,state,postal_code,country,b2b,month,year,design_no.,stock,color,size
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,B09KXVBD7Z,...,MAHARASHTRA,400081.0,IN,False,4,2022,SET389,32.0,White,S
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,B09K3WFS32,...,KARNATAKA,560085.0,IN,False,4,2022,JNE3781,96.0,Green,3XL
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,B07WV4JV4D,...,MAHARASHTRA,410210.0,IN,True,4,2022,JNE3371,4.0,Light Green,XL
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,B099NRCT7B,...,PUDUCHERRY,605008.0,IN,False,4,2022,J0341,193.0,Blue,L
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,B098714BZP,...,TAMIL NADU,600073.0,IN,False,4,2022,JNE3671,6.0,Pink,3XL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128964,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,B098112V2V,...,TELANGANA,500013.0,IN,False,5,2022,JNE3697,69.0,Mauve,XL
128965,402-9551604-7544318,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,B09VC6KHX8,...,HARYANA,122004.0,IN,False,5,2022,SET401,7.0,Black,M
128966,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,B0982YZ51B,...,TELANGANA,500049.0,IN,False,5,2022,J0157,27.0,Black,XXL
128967,402-6184140-0545956,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,B0894Y2NJQ,...,Gujarat,389350.0,IN,False,5,2022,J0012,93.0,Green,XS
128968,408-7436540-8728312,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,B0894X27FC,...,CHHATTISGARH,492014.0,IN,False,5,2022,J0003,9.0,Mustard,S

In [83]:
# Final Dataset Check
sales_analysis.shape
sales_analysis.info()
sales_analysis.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128969 entries, 0 to 128968
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            128969 non-null  object
 1   date                128969 non-null  datetime64[ns]
 2   status              128969 non-null  object
 3   fulfilment          128969 non-null  object
 4   sales_channel       128969 non-null  object
 5   ship_service_level  128969 non-null  object
 6   style               128969 non-null  object
 7   sku                 128969 non-null  object
 8   category            128969 non-null  object
 9   asin                128969 non-null  object
 10  courier_status      128969 non-null  object
 11  quantity            128969 non-null  int64
 12  currency            128969 non-null  object
 13  amount              128969 non-null  float64
 14  city                128969 non-null  object
 15  state               128969 non-null  object
 16  postal_code         128969 non-null  object
 17  country             128969 non-null  object
 18  b2b                 128969 non-null  bool
 19  month               128969 non-null  int32
 20  year                128969 non-null  int32
 21  design_no.          128969 non-null  object
 22  stock               128969 non-null  float64
 23  color               128969 non-null  object
 24  size                128969 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(2), int32(2), int64(1), object(18)
memory usage: 22.8+ MB

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,asin,...,state,postal_code,country,b2b,month,year,design_no.,stock,color,size
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,B09KXVBD7Z,...,MAHARASHTRA,400081.0,IN,False,4,2022,SET389,32.0,White,S
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,B09K3WFS32,...,KARNATAKA,560085.0,IN,False,4,2022,JNE3781,96.0,Green,3XL
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,B07WV4JV4D,...,MAHARASHTRA,410210.0,IN,True,4,2022,JNE3371,4.0,Light Green,XL
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,B099NRCT7B,...,PUDUCHERRY,605008.0,IN,False,4,2022,J0341,193.0,Blue,L
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,B098714BZP,...,TAMIL NADU,600073.0,IN,False,4,2022,JNE3671,6.0,Pink,3XL

In [84]:
# KPIs
# 1. Total revenue
sales_analysis['amount'].sum()

83643634.23343457

In [85]:
# 2. Total orders
sales_analysis['order_id'].nunique()

120378

In [86]:
#3. Total quantity sold
sales_analysis['quantity'].sum()

116646

In [87]:
# Category sales
sales_analysis.groupby('category')['amount'].sum().sort_values(ascending = False)

category
Set              4.130401e+07
kurta            2.334717e+07
Western Dress    1.173233e+07
Top              5.644185e+06
Ethnic Dress     8.340227e+05
Blouse           4.875934e+05
Bottom           1.636392e+05
Saree            1.297708e+05
Dupatta          9.150000e+02
Name: amount, dtype: float64

In [88]:
# State wise sales
sales_analysis.groupby('state')['amount'].sum().sort_values(ascending = False)

state
MAHARASHTRA      1.410444e+07
KARNATAKA        1.108493e+07
TELANGANA        7.366069e+06
UTTAR PRADESH    7.264265e+06
TAMIL NADU       6.952781e+06
                     ...
Pondicherry      5.290000e+02
rajsthan         5.210000e+02
AR               4.930000e+02
Rajsthan         4.430000e+02
PB               3.990000e+02
Name: amount, Length: 70, dtype: float64

In [89]:
# Monthly sales trend
sales_analysis.groupby('month')['amount'].sum()

month
3    1.075209e+05
4    3.078245e+07
5    2.784835e+07
6    2.490531e+07
Name: amount, dtype: float64

In [90]:
# order status analysis
sales_analysis['status'].value_counts()

status
Shipped                          77801
Shipped - Delivered to Buyer     28769
Cancelled                        18329
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [91]:
# B2B vs B2C sales
sales_analysis.groupby('b2b')['amount'].sum()

b2b
False    8.303425e+07
True     6.093805e+05
Name: amount, dtype: float64

In [92]:
# Top 10 products
sales_analysis.groupby('style')['amount'].sum().sort_values(ascending = False).head(10)

style
JNE3797    3.082003e+06
J0230      2.031341e+06
SET268     1.386939e+06
J0341      1.334991e+06
J0003      1.070178e+06
JNE3405    9.499436e+05
J0008      8.639207e+05
SET345     7.869618e+05
SET324     7.706846e+05
JNE3800    7.518097e+05
Name: amount, dtype: float64

In [93]:
# average order value
sales_analysis['amount'].mean()

648.556119946922

In [94]:
# Sales by city
sales_analysis.groupby('city')['amount'].sum().sort_values(ascending = False)

city
BENGALURU                  7.194051e+06
HYDERABAD                  5.249560e+06
MUMBAI                     3.872439e+06
NEW DELHI                  3.837628e+06
CHENNAI                    3.287477e+06
                               ...
Calicut medical college    0.000000e+00
TARBHA                     0.000000e+00
Haringhata                 0.000000e+00
BALAPUR MIDC               0.000000e+00
Kadiri                     0.000000e+00
Name: amount, Length: 8956, dtype: float64

In [95]:
sales_analysis.to_csv("amazon_sales_analysis.csv", index=False)

In [ ]:
# EDA For Pricing Dataset (may)

In [96]:
# Average price per platform
may[['amazon_mrp','flipkart_mrp','myntra_mrp','ajio_mrp']].mean()

amazon_mrp      2237.185094
flipkart_mrp    2232.654382
myntra_mrp      2218.172809
ajio_mrp        2230.688780
dtype: float64

In [97]:
# Max price per platform
may[['amazon_mrp','flipkart_mrp','myntra_mrp','ajio_mrp']].max()

amazon_mrp      5997.0
flipkart_mrp    5997.0
myntra_mrp      5997.0
ajio_mrp        5997.0
dtype: float64

In [98]:
# Price difference amazon vs flipkart
may['price_diff'] = may['amazon_mrp'] - may['flipkart_mrp']
may['price_diff']
may['price_diff'].value_counts

<bound method IndexOpsMixin.value_counts of 0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1325    0.0
1326    0.0
1327    0.0
1328    0.0
1329    0.0
Name: price_diff, Length: 1221, dtype: float64>

In [99]:
# non-zero differences
may[may['price_diff'] != 0][['amazon_mrp','flipkart_mrp','price_diff']].head()

     amazon_mrp  flipkart_mrp  price_diff
341      2395.0        2295.0       100.0
493      1695.0        1795.0      -100.0
494      1695.0        1795.0      -100.0
495      1695.0        1795.0      -100.0
496      1695.0        1795.0      -100.0

In [100]:
may.to_csv("may_price_analysis.csv", index=False)

In [123]:
from sqlalchemy import create_engine

engine = create_engine(
"mysql+mysqlconnector://root:Anjali%40123@localhost:3307/amazon_ecommerce"
)

In [129]:
sales_analysis.to_sql(
    name="sales_analysis",
    con=engine,
    if_exists="replace",
    index=False
)

-1

In [130]:
may.to_sql(
    name="may_price",
    con=engine,
    if_exists="replace",
    index=False
)

-1

In [102]:
sales_analysis.to_csv(r"C:\Users\ac606\OneDrive\Desktop\amazon_sales_analysis.csv", index=False)

In [104]:
may.to_csv(r"C:\Users\ac606\OneDrive\Desktop\may_price_analysis.csv", index=False)